language: go

go:
  - "1.11"
  - "1.12"
  - "1.13"
  - "1.14"
  - "1.15"

env:
  global:
    GO111MODULE: on
    CODECOV_TOKEN: aa7d9225-18d4-412f-afbe-5b6dd20bed13

before_install:
  - go get -t -v ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
